var data = [{'ChartType': 'Line',
 'NewsMedia': 'FiveThirtyEight',
 'Y_AxisLabel': 'e',
 'X_AxisLabel': 'e',
 'Y_GridLines': 'e',
 'ChartTitle': 'e',
 'LegendImplicit': 'r',
 'X_TickMarks': '',
 'Y_AxisTitle': 'e',
 'X_Axis': 'e',
 'DataLabel': '',
 'X_GridLines': 'e',
 'X_AxisTitle': '',
 'Y_Axis': '',
 'LegendExplicit': '',
 'Y_TickMarks': '',
 'Highlight': 'r',
 'Exp.text': 'e',
 'GNRD': 'a',
 'HRO': 'e',
 'RowSum': 3,
 'Modified': 'TRUE',
 'Cropped': '',
 'Resized': '',
 'URL': '<a href=https://fivethirtyeight.com/features/how-cable-news-covered-mueller-in-2018/> Link </a>',
 'id': 'tbl1_1'},
 {'ChartType': 'Line',
  'NewsMedia': 'FiveThirtyEight',
  'Y_AxisLabel': 'e',
  'X_AxisLabel': 'e',
  'Y_GridLines': 'e',
  'ChartTitle': 'a',
  'LegendImplicit': 'r',
  'X_TickMarks': '',
  'Y_AxisTitle': '',
  'X_Axis': 'e',
  'DataLabel': 'r',
  'X_GridLines': 'e',
  'X_AxisTitle': '',
  'Y_Axis': 'e',
  'LegendExplicit': 'e',
  'Y_TickMarks': '',
  'Highlight': 'e',
  'Exp.text': 'e',
  'GNRD': '',
  'HRO': '',
  'RowSum': 3,
  'Modified': 'TRUE',
  'Cropped': 'TRUE',
  'Resized': '',
  'URL': '<a href=https://projects.fivethirtyeight.com/trump-approval-ratings/?ex_cid=rrpromo> Link </a>',
  'id': 'tbl1_2'},
 {'ChartType': 'Line',
  'NewsMedia': 'FiveThirtyEight',
  'Y_AxisLabel': 'e',
  'X_AxisLabel': 'e',
  'Y_GridLines': 'e',
  'ChartTitle': 'e',
  'LegendImplicit': 'r',
  'X_TickMarks': '',
  'Y_AxisTitle': '',
  'X_Axis': 'e',
  'DataLabel': 'r',
  'X_GridLines': 'e',
  'X_AxisTitle': '',
  'Y_Axis': 'e',
  'LegendExplicit': 'e',
  'Y_TickMarks': '',
  'Highlight': 'r',
  'Exp.text': 'e',
  'GNRD': '',
  'HRO': '',
  'RowSum': 3,
  'Modified': 'TRUE',
  'Cropped': '',
  'Resized': '',
  'URL': '<a href=https://projects.fivethirtyeight.com/congress-generic-ballot-polls/?ex_cid=rrpromo> Link </a>',
  'id': 'tbl1_3'},
 {'ChartType': 'Line',
  'NewsMedia': 'FiveThirtyEight',
  'Y_AxisLabel': '',
  'X_AxisLabel': '',
  'Y_GridLines': 'e',
  'ChartTitle': 'e',
  'LegendImplicit': 'e',
  'X_TickMarks': '',
  'Y_AxisTitle': '',
  'X_Axis': '',
  'DataLabel': '',
  'X_GridLines': 'e',
  'X_AxisTitle': '',
  'Y_Axis': '',
  'LegendExplicit': '',
  'Y_TickMarks': '',
  'Highlight': '',
  'Exp.text': 'e',
  'GNRD': '',
  'HRO': 'a',
  'RowSum': 1,
  'Modified': 'TRUE',
  'Cropped': '',
  'Resized': '',
  'URL': '<a href=https://fivethirtyeight.com/features/what-reddit-can-tell-us-about-nba-fan-bases/> Link </a>',
  'id': 'tbl1_4'},
 {'ChartType': 'Line',
  'NewsMedia': 'Pew Research Center',
  'Y_AxisLabel': '',
  'X_AxisLabel': '',
  'Y_GridLines': 'r',
  'ChartTitle': 'e',
  'LegendImplicit': '',
  'X_TickMarks': '',
  'Y_AxisTitle': 'r',
  'X_Axis': 'r',
  'DataLabel': 'r',
  'X_GridLines': '',
  'X_AxisTitle': '',
  'Y_Axis': '',
  'LegendExplicit': '',
  'Y_TickMarks': '',
  'Highlight': '',
  'Exp.text': '',
  'GNRD': '',
  'HRO': '',
  'RowSum': 4,
  'Modified': 'TRUE',
  'Cropped': '',
  'Resized': '',
  'URL': '<a href=http://www.pewhispanic.org/2018/11/27/u-s-unauthorized-immigrant-total-dips-to-lowest-level-in-a-decade/> Link </a>',
  'id': 'tbl1_5'},
 {'ChartType': 'Line',
  'NewsMedia': 'The Economist',
  'Y_AxisLabel': 'r',
  'X_AxisLabel': 'r',
  'Y_GridLines': 'r',
  'ChartTitle': 'r',
  'LegendImplicit': 'r',
  'X_TickMarks': 'r',
  'Y_AxisTitle': 'r',
  'X_Axis': 'r',
  'DataLabel': '',
  'X_GridLines': '',
  'X_AxisTitle': '',
  'Y_Axis': '',
  'LegendExplicit': '',
  'Y_TickMarks': '',
  'Highlight': 'r',
  'Exp.text': 'r',
  'GNRD': '',
  'HRO': '',
  'RowSum': 10,
  'Modified': '',
  'Cropped': '',
  'Resized': 'TRUE',
  'URL': '<a href=https://www.economist.com/graphic-detail/2018/11/20/competition-is-withering-on-both-sides-of-the-atlantic> Link </a>',
  'id': 'tbl1_6'},
 {'ChartType': 'Line',
  'NewsMedia': 'The Economist',
  'Y_AxisLabel': 'r',
  'X_AxisLabel': 'r',
  'Y_GridLines': 'r',
  'ChartTitle': 'r',
  'LegendImplicit': 'r',
  'X_TickMarks': 'r',
  'Y_AxisTitle': 'r',
  'X_Axis': 'r',
  'DataLabel': '',
  'X_GridLines': '',
  'X_AxisTitle': '',
  'Y_Axis': '',
  'LegendExplicit': '',
  'Y_TickMarks': '',
  'Highlight': '',
  'Exp.text': '',
  'GNRD': '',
  'HRO': '',
  'RowSum': 8,
  'Modified': '',
  'Cropped': '',
  'Resized': 'TRUE',
  'URL': '<a href=https://www.economist.com/finance-and-economics/2018/12/22/why-americans-and-britons-work-such-long-hours> Link </a>',
  'id': 'tbl1_7'},
 {'ChartType': 'Line',
  'NewsMedia': 'The Economist',
  'Y_AxisLabel': 'r',
  'X_AxisLabel': 'r',
  'Y_GridLines': 'r',
  'ChartTitle': 'r',
  'LegendImplicit': 'r',
  'X_TickMarks': 'r',
  'Y_AxisTitle': 'r',
  'X_Axis': 'r',
  'DataLabel': '',
  'X_GridLines': '',
  'X_AxisTitle': '',
  'Y_Axis': '',
  'LegendExplicit': '',
  'Y_TickMarks': '',
  'Highlight': '',
  'Exp.text': '',
  'GNRD': '',
  'HRO': '',
  'RowSum': 8,
  'Modified': '',
  'Cropped': '',
  'Resized': 'TRUE',
  'URL': '<a href=https://www.economist.com/graphic-detail/2018/12/28/why-do-some-countries-work-longer-hours-than-others> Link </a>',
  'id': 'tbl1_8'},
 {'ChartType': 'Line',
  'NewsMedia': 'The Economist',
  'Y_AxisLabel': 'r',
  'X_AxisLabel': 'r',
  'Y_GridLines': 'e',
  'ChartTitle': '',
  'LegendImplicit': 'r',
  'X_TickMarks': '',
  'Y_AxisTitle': '',
  'X_Axis': 'e',
  'DataLabel': 'r',
  'X_GridLines': 'r',
  'X_AxisTitle': 'e',
  'Y_Axis': '',
  'LegendExplicit': '',
  'Y_TickMarks': '',
  'Highlight': 'r',
  'Exp.text': 'r',
  'GNRD': '',
  'HRO': '',
  'RowSum': 7,
  'Modified': 'TRUE',
  'Cropped': 'TRUE',
  'Resized': '',
  'URL': '<a href=https://www.economist.com/graphic-detail/2018/12/15/gdp-predictions-are-reliable-only-in-the-short-term> Link </a>',
  'id': 'tbl1_9'},
 {'ChartType': 'Line',
  'NewsMedia': 'The Economist',
  'Y_AxisLabel': '',
  'X_AxisLabel': '',
  'Y_GridLines': 'r',
  'ChartTitle': '',
  'LegendImplicit': 'r',
  'X_TickMarks': '',
  'Y_AxisTitle': 'r',
  'X_Axis': '',
  'DataLabel': '',
  'X_GridLines': '',
  'X_AxisTitle': '',
  'Y_Axis': '',
  'LegendExplicit': '',
  'Y_TickMarks': '',
  'Highlight': 'r',
  'Exp.text': 'r',
  'GNRD': '',
  'HRO': '',
  'RowSum': 5,
  'Modified': 'TRUE',
  'Cropped': '',
  'Resized': '',
  'URL': '<a href=https://www.economist.com/graphic-detail/2018/12/18/the-news-events-that-most-engrossed-audiences-in-2018> Link </a>',
  'id': 'tbl1_10'},
 {'ChartType': 'Line',
  'NewsMedia': 'The Economist',
  'Y_AxisLabel': 'r',
  'X_AxisLabel': 'r',
  'Y_GridLines': 'e',
  'ChartTitle': 'r',
  'LegendImplicit': 'r',
  'X_TickMarks': 'e',
  'Y_AxisTitle': 'r',
  'X_Axis': 'e',
  'DataLabel': '',
  'X_GridLines': '',
  'X_AxisTitle': '',
  'Y_Axis': '',
  'LegendExplicit': '',
  'Y_TickMarks': '',
  'Highlight': '',
  'Exp.text': '',
  'GNRD': '',
  'HRO': '',
  'RowSum': 5,
  'Modified': '',
  'Cropped': 'TRUE',
  'Resized': '',
  'URL': '<a href=https://www.economist.com/graphic-detail/2018/11/26/suicides-are-declining-around-the-world> Link </a>',
  'id': 'tbl1_11'},
 {'ChartType': 'Line',
  'NewsMedia': 'The New York Times',
  'Y_AxisLabel': 'r',
  'X_AxisLabel': 'r',
  'Y_GridLines': 'r',
  'ChartTitle': 'r',
  'LegendImplicit': 'r',
  'X_TickMarks': 'r',
  'Y_AxisTitle': '',
  'X_Axis': 'r',
  'DataLabel': '',
  'X_GridLines': '',
  'X_AxisTitle': '',
  'Y_Axis': '',
  'LegendExplicit': '',
  'Y_TickMarks': '',
  'Highlight': 'r',
  'Exp.text': 'r',
  'GNRD': '',
  'HRO': '',
  'RowSum': 9,
  'Modified': '',
  'Cropped': '',
  'Resized': 'TRUE',
  'URL': '<a href=https://www.nytimes.com/2018/12/19/business/dealbook/fed-rate-increases-markets.html> Link </a>',
  'id': 'tbl1_12'},
 {'ChartType': 'Line',
  'NewsMedia': 'The New York Times',
  'Y_AxisLabel': 'r',
  'X_AxisLabel': 'r',
  'Y_GridLines': 'r',
  'ChartTitle': 'a',
  'LegendImplicit': 'r',
  'X_TickMarks': 'r',
  'Y_AxisTitle': 'r',
  'X_Axis': 'r',
  'DataLabel': '',
  'X_GridLines': '',
  'X_AxisTitle': '',
  'Y_Axis': '',
  'LegendExplicit': '',
  'Y_TickMarks': '',
  'Highlight': 'r',
  'Exp.text': '',
  'GNRD': '',
  'HRO': '',
  'RowSum': 9,
  'Modified': 'TRUE',
  'Cropped': '',
  'Resized': 'TRUE',
  'URL': '<a href=https://www.nytimes.com/2018/11/27/business/dealbook/apple-microsoft-stock.html> Link </a>',
  'id': 'tbl1_13'},
 {'ChartType': 'Line',
  'NewsMedia': 'The New York Times',
  'Y_AxisLabel': 'r',
  'X_AxisLabel': 'r',
  'Y_GridLines': 'r',
  'ChartTitle': 'r',
  'LegendImplicit': '',
  'X_TickMarks': 'r',
  'Y_AxisTitle': 'r',
  'X_Axis': '',
  'DataLabel': 'r',
  'X_GridLines': '',
  'X_AxisTitle': '',
  'Y_Axis': '',
  'LegendExplicit': '',
  'Y_TickMarks': '',
  'Highlight': 'r',
  'Exp.text': 'r',
  'GNRD': '',
  'HRO': '',
  'RowSum': 9,
  'Modified': '',
  'Cropped': '',
  'Resized': 'TRUE',
  'URL': '<a href=https://www.nytimes.com/2018/11/29/business/dealbook/oil-price-junk-bonds.html> Link </a>',
  'id': 'tbl1_14'},
 {'ChartType': 'Line',
  'NewsMedia': 'The New York Times',
  'Y_AxisLabel': 'r',
  'X_AxisLabel': 'r',
  'Y_GridLines': 'r',
  'ChartTitle': 'r',
  'LegendImplicit': '',
  'X_TickMarks': 'r',
  'Y_AxisTitle': '',
  'X_Axis': '',
  'DataLabel': 'r',
  'X_GridLines': '',
  'X_AxisTitle': '',
  'Y_Axis': '',
  'LegendExplicit': '',
  'Y_TickMarks': '',
  'Highlight': 'r',
  'Exp.text': 'r',
  'GNRD': '',
  'HRO': '',
  'RowSum': 8,
  'Modified': '',
  'Cropped': '',
  'Resized': 'TRUE',
  'URL': '<a href=https://www.nytimes.com/2018/12/06/business/dealbook/trump-federal-reserve-interest-rates.html> Link </a>',
  'id': 'tbl1_15'},
 {'ChartType': 'Line',
  'NewsMedia': 'The New York Times',
  'Y_AxisLabel': 'r',
  'X_AxisLabel': 'r',
  'Y_GridLines': 'r',
  'ChartTitle': 'e',
  'LegendImplicit': 'r',
  'X_TickMarks': 'r',
  'Y_AxisTitle': 'r',
  'X_Axis': '',
  'DataLabel': '',
  'X_GridLines': '',
  'X_AxisTitle': '',
  'Y_Axis': '',
  'LegendExplicit': '',
  'Y_TickMarks': '',
  'Highlight': 'r',
  'Exp.text': 'r',
  'GNRD': '',
  'HRO': '',
  'RowSum': 8,
  'Modified': '',
  'Cropped': 'TRUE',
  'Resized': '',
  'URL': '<a href=https://www.nytimes.com/2018/12/13/business/dealbook/china-markets-stocks-trade.html> Link </a>',
  'id': 'tbl1_16'},
 {'ChartType': 'Line',
  'NewsMedia': 'The New York Times',
  'Y_AxisLabel': 'r',
  'X_AxisLabel': 'r',
  'Y_GridLines': 'r',
  'ChartTitle': 'a',
  'LegendImplicit': 'r',
  'X_TickMarks': 'r',
  'Y_AxisTitle': 'r',
  'X_Axis': '',
  'DataLabel': '',
  'X_GridLines': '',
  'X_AxisTitle': '',
  'Y_Axis': '',
  'LegendExplicit': '',
  'Y_TickMarks': '',
  'Highlight': 'r',
  'Exp.text': '',
  'GNRD': '',
  'HRO': '',
  'RowSum': 8,
  'Modified': 'TRUE',
  'Cropped': '',
  'Resized': '',
  'URL': '<a href=https://www.nytimes.com/2018/12/17/business/dealbook/obamacare-ruling-health-care-stocks.html> Link </a>',
  'id': 'tbl1_17'},
 {'ChartType': 'Line',
  'NewsMedia': 'The New York Times',
  'Y_AxisLabel': 'r',
  'X_AxisLabel': 'r',
  'Y_GridLines': 'r',
  'ChartTitle': '',
  'LegendImplicit': '',
  'X_TickMarks': 'r',
  'Y_AxisTitle': 'r',
  'X_Axis': 'r',
  'DataLabel': 'e',
  'X_GridLines': '',
  'X_AxisTitle': '',
  'Y_Axis': '',
  'LegendExplicit': '',
  'Y_TickMarks': '',
  'Highlight': 'r',
  'Exp.text': 'r',
  'GNRD': '',
  'HRO': '',
  'RowSum': 8,
  'Modified': '',
  'Cropped': 'TRUE',
  'Resized': '',
  'URL': '<a href=https://www.nytimes.com/2018/11/20/business/dealbook/5-tech-stocks-combined-lost-800-billion.html> Link </a>',
  'id': 'tbl1_18'},
 {'ChartType': 'Line',
  'NewsMedia': 'The New York Times',
  'Y_AxisLabel': 'r',
  'X_AxisLabel': 'r',
  'Y_GridLines': 'r',
  'ChartTitle': 'e',
  'LegendImplicit': '',
  'X_TickMarks': 'r',
  'Y_AxisTitle': 'r',
  'X_Axis': '',
  'DataLabel': 'r',
  'X_GridLines': '',
  'X_AxisTitle': '',
  'Y_Axis': '',
  'LegendExplicit': '',
  'Y_TickMarks': '',
  'Highlight': 'r',
  'Exp.text': 'r',
  'GNRD': '',
  'HRO': '',
  'RowSum': 8,
  'Modified': '',
  'Cropped': 'TRUE',
  'Resized': '',
  'URL': '<a href=https://www.nytimes.com/2018/11/28/business/dealbook/inflation-expectations-fed.html> Link </a>',
  'id': 'tbl1_19'},
 {'ChartType': 'Line',
  'NewsMedia': 'The New York Times',
  'Y_AxisLabel': 'r',
  'X_AxisLabel': 'r',
  'Y_GridLines': 'r',
  'ChartTitle': 'r',
  'LegendImplicit': 'r',
  'X_TickMarks': 'e',
  'Y_AxisTitle': 'r',
  'X_Axis': '',
  'DataLabel': '',
  'X_GridLines': '',
  'X_AxisTitle': '',
  'Y_Axis': '',
  'LegendExplicit': '',
  'Y_TickMarks': '',
  'Highlight': '',
  'Exp.text': 'r',
  'GNRD': '',
  'HRO': '',
  'RowSum': 7,
  'Modified': 'TRUE',
  'Cropped': '',
  'Resized': 'TRUE',
  'URL': '<a href=https://www.nytimes.com/interactive/2018/12/10/business/dealbook/stock-market-correction-long-term.html> Link </a>',
  'id': 'tbl1_20'},
 {'ChartType': 'Line',
  'NewsMedia': 'The New York Times',
  'Y_AxisLabel': 'r',
  'X_AxisLabel': 'r',
  'Y_GridLines': 'r',
  'ChartTitle': '',
  'LegendImplicit': '',
  'X_TickMarks': 'r',
  'Y_AxisTitle': '',
  'X_Axis': '',
  'DataLabel': 'r',
  'X_GridLines': '',
  'X_AxisTitle': '',
  'Y_Axis': '',
  'LegendExplicit': '',
  'Y_TickMarks': '',
  'Highlight': 'r',
  'Exp.text': 'r',
  'GNRD': '',
  'HRO': '',
  'RowSum': 7,
  'Modified': '',
  'Cropped': '',
  'Resized': 'TRUE',
  'URL': '<a href=https://www.nytimes.com/2018/11/07/business/election-markets.html> Link </a>',
  'id': 'tbl1_21'},
 {'ChartType': 'Line',
  'NewsMedia': 'The New York Times',
  'Y_AxisLabel': 'r',
  'X_AxisLabel': 'r',
  'Y_GridLines': 'r',
  'ChartTitle': 'e',
  'LegendImplicit': 'r',
  'X_TickMarks': 'r',
  'Y_AxisTitle': 'e',
  'X_Axis': 'r',
  'DataLabel': '',
  'X_GridLines': '',
  'X_AxisTitle': '',
  'Y_Axis': '',
  'LegendExplicit': '',
  'Y_TickMarks': '',
  'Highlight': 'r',
  'Exp.text': 'e',
  'GNRD': '',
  'HRO': '',
  'RowSum': 7,
  'Modified': '',
  'Cropped': 'TRUE',
  'Resized': '',
  'URL': '<a href=https://www.nytimes.com/2018/11/12/upshot/why-prescription-drug-spending-higher-in-the-us.html> Link </a>',
  'id': 'tbl1_22'},
 {'ChartType': 'Line',
  'NewsMedia': 'The New York Times',
  'Y_AxisLabel': 'r',
  'X_AxisLabel': 'r',
  'Y_GridLines': 'r',
  'ChartTitle': 'e',
  'LegendImplicit': 'r',
  'X_TickMarks': 'r',
  'Y_AxisTitle': '',
  'X_Axis': '',
  'DataLabel': '',
  'X_GridLines': '',
  'X_AxisTitle': '',
  'Y_Axis': '',
  'LegendExplicit': '',
  'Y_TickMarks': '',
  'Highlight': 'r',
  'Exp.text': 'e',
  'GNRD': '',
  'HRO': '',
  'RowSum': 6,
  'Modified': '',
  'Cropped': 'TRUE',
  'Resized': '',
  'URL': '<a href=https://www.nytimes.com/2018/12/04/business/dealbook/bank-stocks-bond-yields.html> Link </a>',
  'id': 'tbl1_23'},
 {'ChartType': 'Line',
  'NewsMedia': 'The New York Times',
  'Y_AxisLabel': 'r',
  'X_AxisLabel': 'r',
  'Y_GridLines': 'r',
  'ChartTitle': 'r',
  'LegendImplicit': 'r',
  'X_TickMarks': '',
  'Y_AxisTitle': '',
  'X_Axis': '',
  'DataLabel': '',
  'X_GridLines': '',
  'X_AxisTitle': '',
  'Y_Axis': '',
  'LegendExplicit': '',
  'Y_TickMarks': '',
  'Highlight': 'r',
  'Exp.text': 'e',
  'GNRD': '',
  'HRO': '',
  'RowSum': 6,
  'Modified': 'TRUE',
  'Cropped': '',
  'Resized': '',
  'URL': '<a href=https://www.nytimes.com/interactive/2018/12/14/us/politics/gun-control-laws.html> Link </a>',
  'id': 'tbl1_24'},
 {'ChartType': 'Line',
  'NewsMedia': 'The New York Times',
  'Y_AxisLabel': 'r',
  'X_AxisLabel': '',
  'Y_GridLines': 'r',
  'ChartTitle': '',
  'LegendImplicit': '',
  'X_TickMarks': 'r',
  'Y_AxisTitle': 'e',
  'X_Axis': 'r',
  'DataLabel': '',
  'X_GridLines': '',
  'X_AxisTitle': '',
  'Y_Axis': '',
  'LegendExplicit': '',
  'Y_TickMarks': '',
  'Highlight': '',
  'Exp.text': 'r',
  'GNRD': '',
  'HRO': '',
  'RowSum': 5,
  'Modified': '',
  'Cropped': 'TRUE',
  'Resized': '',
  'URL': '<a href=https://www.nytimes.com/2018/12/14/business/dealbook/stock-market-volatility.html> Link </a>',
  'id': 'tbl1_25'},
 {'ChartType': 'Line',
  'NewsMedia': 'The New York Times',
  'Y_AxisLabel': 'e',
  'X_AxisLabel': 'r',
  'Y_GridLines': 'r',
  'ChartTitle': '',
  'LegendImplicit': '',
  'X_TickMarks': 'r',
  'Y_AxisTitle': '',
  'X_Axis': '',
  'DataLabel': 'r',
  'X_GridLines': '',
  'X_AxisTitle': '',
  'Y_Axis': '',
  'LegendExplicit': '',
  'Y_TickMarks': '',
  'Highlight': 'r',
  'Exp.text': 'e',
  'GNRD': '',
  'HRO': '',
  'RowSum': 5,
  'Modified': '',
  'Cropped': 'TRUE',
  'Resized': '',
  'URL': '<a href=https://www.nytimes.com/2018/11/15/business/dealbook/britain-pound-brexit.html> Link </a>',
  'id': 'tbl1_26'},
 {'ChartType': 'Line',
  'NewsMedia': 'The New York Times',
  'Y_AxisLabel': 'r',
  'X_AxisLabel': 'r',
  'Y_GridLines': 'e',
  'ChartTitle': 'e',
  'LegendImplicit': 'r',
  'X_TickMarks': 'e',
  'Y_AxisTitle': '',
  'X_Axis': 'e',
  'DataLabel': 'r',
  'X_GridLines': '',
  'X_AxisTitle': '',
  'Y_Axis': '',
  'LegendExplicit': '',
  'Y_TickMarks': '',
  'Highlight': '',
  'Exp.text': 'r',
  'GNRD': '',
  'HRO': '',
  'RowSum': 5,
  'Modified': '',
  'Cropped': 'TRUE',
  'Resized': '',
  'URL': '<a href=https://www.nytimes.com/interactive/2018/11/29/upshot/fentanyl-drug-overdose-deaths.html> Link </a>',
  'id': 'tbl1_27'},
 {'ChartType': 'Line',
  'NewsMedia': 'The Wall Street Journal',
  'Y_AxisLabel': 'r',
  'X_AxisLabel': 'r',
  'Y_GridLines': 'r',
  'ChartTitle': '',
  'LegendImplicit': 'r',
  'X_TickMarks': 'r',
  'Y_AxisTitle': 'r',
  'X_Axis': 'r',
  'DataLabel': '',
  'X_GridLines': '',
  'X_AxisTitle': '',
  'Y_Axis': '',
  'LegendExplicit': '',
  'Y_TickMarks': '',
  'Highlight': 'r',
  'Exp.text': 'r',
  'GNRD': '',
  'HRO': '',
  'RowSum': 9,
  'Modified': '',
  'Cropped': 'TRUE',
  'Resized': '',
  'URL': '<a href=https://www.wsj.com/graphics/nafta-2018/> Link </a>',
  'id': 'tbl1_28'},
 {'ChartType': 'Line',
  'NewsMedia': 'The Wall Street Journal',
  'Y_AxisLabel': 'r',
  'X_AxisLabel': 'r',
  'Y_GridLines': 'r',
  'ChartTitle': '',
  'LegendImplicit': '',
  'X_TickMarks': 'r',
  'Y_AxisTitle': 'r',
  'X_Axis': 'r',
  'DataLabel': '',
  'X_GridLines': '',
  'X_AxisTitle': '',
  'Y_Axis': '',
  'LegendExplicit': 'r',
  'Y_TickMarks': '',
  'Highlight': '',
  'Exp.text': '',
  'GNRD': '',
  'HRO': '',
  'RowSum': 7,
  'Modified': 'TRUE',
  'Cropped': '',
  'Resized': '',
  'URL': '<a href=https://www.wsj.com/graphics/how-does-your-city-compare-to-latin-american-violence/> Link </a>',
  'id': 'tbl1_29'},
 {'ChartType': 'Line',
  'NewsMedia': 'The Wall Street Journal',
  'Y_AxisLabel': '',
  'X_AxisLabel': '',
  'Y_GridLines': 'r',
  'ChartTitle': '',
  'LegendImplicit': 'r',
  'X_TickMarks': 'r',
  'Y_AxisTitle': '',
  'X_Axis': '',
  'DataLabel': '',
  'X_GridLines': '',
  'X_AxisTitle': '',
  'Y_Axis': '',
  'LegendExplicit': '',
  'Y_TickMarks': '',
  'Highlight': 'r',
  'Exp.text': 'e',
  'GNRD': '',
  'HRO': '',
  'RowSum': 4,
  'Modified': '',
  'Cropped': '',
  'Resized': 'TRUE',
  'URL': '<a href=https://www.wsj.com/graphics/how-money-flowed-and-ebbed-at-ge/> Link </a>',
  'id': 'tbl1_30'},
 {'ChartType': 'Bar',
  'NewsMedia': 'Bloomberg',
  'Y_AxisLabel': 'r',
  'X_AxisLabel': 'r',
  'Y_GridLines': 'r',
  'ChartTitle': 'e',
  'LegendImplicit': 'r',
  'X_TickMarks': 'r',
  'Y_AxisTitle': '',
  'X_Axis': 'r',
  'DataLabel': '',
  'X_GridLines': '',
  'X_AxisTitle': '',
  'Y_Axis': '',
  'LegendExplicit': '',
  'Y_TickMarks': '',
  'Highlight': '',
  'Exp.text': 'e',
  'GNRD': '',
  'HRO': '',
  'RowSum': 6,
  'Modified': '',
  'Cropped': 'TRUE',
  'Resized': '',
  'URL': '<a href=https://www.BBG.com/graphics/2018-house-seats-vs-votes/> Link </a>',
  'id': 'tbl1_31'},
 {'ChartType': 'Bar',
  'NewsMedia': 'Bloomberg',
  'Y_AxisLabel': 'r',
  'X_AxisLabel': 'r',
  'Y_GridLines': 'e',
  'ChartTitle': 'e',
  'LegendImplicit': '',
  'X_TickMarks': 'e',
  'Y_AxisTitle': '',
  'X_Axis': 'r',
  'DataLabel': '',
  'X_GridLines': '',
  'X_AxisTitle': '',
  'Y_Axis': '',
  'LegendExplicit': '',
  'Y_TickMarks': '',
  'Highlight': '',
  'Exp.text': '',
  'GNRD': '',
  'HRO': '',
  'RowSum': 3,
  'Modified': '',
  'Cropped': 'TRUE',
  'Resized': '',
  'URL': '<a href=https://www.BBG.com/graphics/etf-fund-flows/> Link </a>',
  'id': 'tbl1_32'},
 {'ChartType': 'Bar',
  'NewsMedia': 'First Tuesday Journal',
  'Y_AxisLabel': 'r',
  'X_AxisLabel': 'r',
  'Y_GridLines': 'r',
  'ChartTitle': 'r',
  'LegendImplicit': '',
  'X_TickMarks': 'r',
  'Y_AxisTitle': '',
  'X_Axis': 'r',
  'DataLabel': '',
  'X_GridLines': 'r',
  'X_AxisTitle': '',
  'Y_Axis': 'r',
  'LegendExplicit': 'r',
  'Y_TickMarks': '',
  'Highlight': '',
  'Exp.text': 'r',
  'GNRD': '',
  'HRO': '',
  'RowSum': 10,
  'Modified': '',
  'Cropped': '',
  'Resized': 'TRUE',
  'URL': '<a href=http://journal.firsttuesday.us/the-distribution-of-californias-human-resources/10315/> Link </a>',
  'id': 'tbl1_33'},
 {'ChartType': 'Bar',
  'NewsMedia': 'First Tuesday Journal',
  'Y_AxisLabel': '',
  'X_AxisLabel': '',
  'Y_GridLines': '',
  'ChartTitle': 'r',
  'LegendImplicit': '',
  'X_TickMarks': '',
  'Y_AxisTitle': '',
  'X_Axis': '',
  'DataLabel': 'r',
  'X_GridLines': '',
  'X_AxisTitle': '',
  'Y_Axis': '',
  'LegendExplicit': '',
  'Y_TickMarks': '',
  'Highlight': '',
  'Exp.text': 'r',
  'GNRD': 'r',
  'HRO': '',
  'RowSum': 4,
  'Modified': '',
  'Cropped': '',
  'Resized': 'TRUE',
  'URL': '<a href=http://journal.firsttuesday.us/the-votes-are-in-landlords-and-tenants-drag-their-feet-on-renters-insurance/65732/> Link </a>',
  'id': 'tbl1_34'},
 {'ChartType': 'Bar',
  'NewsMedia': 'FiveThirtyEight',
  'Y_AxisLabel': 'e',
  'X_AxisLabel': 'e',
  'Y_GridLines': 'e',
  'ChartTitle': 'e',
  'LegendImplicit': '',
  'X_TickMarks': '',
  'Y_AxisTitle': '',
  'X_Axis': '',
  'DataLabel': '',
  'X_GridLines': 'e',
  'X_AxisTitle': 'e',
  'Y_Axis': 'r',
  'LegendExplicit': '',
  'Y_TickMarks': '',
  'Highlight': 'r',
  'Exp.text': 'e',
  'GNRD': '',
  'HRO': '',
  'RowSum': 2,
  'Modified': 'TRUE',
  'Cropped': '',
  'Resized': '',
  'URL': '<a href=https://fivethirtyeight.com/features/the-2018-midterms-in-4-charts/> Link </a>',
  'id': 'tbl1_35'},
 {'ChartType': 'Bar',
  'NewsMedia': 'Pew Research Center',
  'Y_AxisLabel': 'r',
  'X_AxisLabel': '',
  'Y_GridLines': '',
  'ChartTitle': 'e',
  'LegendImplicit': 'r',
  'X_TickMarks': '',
  'Y_AxisTitle': '',
  'X_Axis': '',
  'DataLabel': 'r',
  'X_GridLines': '',
  'X_AxisTitle': 'r',
  'Y_Axis': 'r',
  'LegendExplicit': '',
  'Y_TickMarks': '',
  'Highlight': '',
  'Exp.text': 'e',
  'GNRD': '',
  'HRO': '',
  'RowSum': 5,
  'Modified': 'TRUE',
  'Cropped': '',
  'Resized': '',
  'URL': '<a href=http://www.people-press.org/2018/11/15/public-expects-gridlock-deeper-divisions-with-changed-political-landscape/> Link </a>',
  'id': 'tbl1_36'},
 {'ChartType': 'Bar',
  'NewsMedia': 'Pew Research Center',
  'Y_AxisLabel': '',
  'X_AxisLabel': '',
  'Y_GridLines': 'r',
  'ChartTitle': 'e',
  'LegendImplicit': '',
  'X_TickMarks': '',
  'Y_AxisTitle': 'r',
  'X_Axis': 'r',
  'DataLabel': 'r',
  'X_GridLines': '',
  'X_AxisTitle': '',
  'Y_Axis': '',
  'LegendExplicit': '',
  'Y_TickMarks': '',
  'Highlight': '',
  'Exp.text': 'e',
  'GNRD': '',
  'HRO': '',
  'RowSum': 4,
  'Modified': 'TRUE',
  'Cropped': '',
  'Resized': '',
  'URL': '<a href=http://www.journalism.org/2018/12/03/americans-still-prefer-watching-to-reading-the-news-and-mostly-still-through-television/> Link </a>',
  'id': 'tbl1_37'},
 {'ChartType': 'Bar',
  'NewsMedia': 'Pew Research Center',
  'Y_AxisLabel': '',
  'X_AxisLabel': '',
  'Y_GridLines': '',
  'ChartTitle': 'e',
  'LegendImplicit': '',
  'X_TickMarks': '',
  'Y_AxisTitle': '',
  'X_Axis': '',
  'DataLabel': 'r',
  'X_GridLines': '',
  'X_AxisTitle': 'r',
  'Y_Axis': '',
  'LegendExplicit': 'r',
  'Y_TickMarks': '',
  'Highlight': '',
  'Exp.text': 'e',
  'GNRD': '',
  'HRO': '',
  'RowSum': 3,
  'Modified': 'TRUE',
  'Cropped': '',
  'Resized': '',
  'URL': '<a href=http://www.people-press.org/2018/12/17/most-voters-have-positive-views-of-their-midterm-voting-experiences/> Link </a>',
  'id': 'tbl1_38'},
 {'ChartType': 'Bar',
  'NewsMedia': 'Pew Research Center',
  'Y_AxisLabel': 'r',
  'X_AxisLabel': '',
  'Y_GridLines': '',
  'ChartTitle': 'e',
  'LegendImplicit': 'e',
  'X_TickMarks': '',
  'Y_AxisTitle': '',
  'X_Axis': '',
  'DataLabel': 'r',
  'X_GridLines': '',
  'X_AxisTitle': 'r',
  'Y_Axis': '',
  'LegendExplicit': '',
  'Y_TickMarks': '',
  'Highlight': '',
  'Exp.text': 'e',
  'GNRD': '',
  'HRO': 'e',
  'RowSum': 3,
  'Modified': 'TRUE',
  'Cropped': '',
  'Resized': '',
  'URL': '<a href=http://www.pewinternet.org/2018/11/16/public-attitudes-toward-computer-algorithms/> Link </a>',
  'id': 'tbl1_39'},
 {'ChartType': 'Bar',
  'NewsMedia': 'The Economist',
  'Y_AxisLabel': 'r',
  'X_AxisLabel': '',
  'Y_GridLines': 'r',
  'ChartTitle': 'r',
  'LegendImplicit': '',
  'X_TickMarks': '',
  'Y_AxisTitle': 'r',
  'X_Axis': 'r',
  'DataLabel': 'r',
  'X_GridLines': 'r',
  'X_AxisTitle': '',
  'Y_Axis': '',
  'LegendExplicit': '',
  'Y_TickMarks': 'r',
  'Highlight': '',
  'Exp.text': 'r',
  'GNRD': '',
  'HRO': 'r',
  'RowSum': 10,
  'Modified': '',
  'Cropped': 'TRUE',
  'Resized': '',
  'URL': '<a href=https://www.economist.com/graphic-detail/2018/12/31/a-picture-of-probabilities> Link </a>',
  'id': 'tbl1_40'},
 {'ChartType': 'Bar',
  'NewsMedia': 'The Economist',
  'Y_AxisLabel': 'r',
  'X_AxisLabel': '',
  'Y_GridLines': 'r',
  'ChartTitle': 'r',
  'LegendImplicit': '',
  'X_TickMarks': '',
  'Y_AxisTitle': '',
  'X_Axis': '',
  'DataLabel': 'r',
  'X_GridLines': 'r',
  'X_AxisTitle': 'r',
  'Y_Axis': 'r',
  'LegendExplicit': '',
  'Y_TickMarks': '',
  'Highlight': 'r',
  'Exp.text': 'r',
  'GNRD': '',
  'HRO': '',
  'RowSum': 9,
  'Modified': '',
  'Cropped': 'TRUE',
  'Resized': '',
  'URL': '<a href=https://www.economist.com/graphic-detail/2018/12/25/the-economists-word-of-the-year> Link </a>',
  'id': 'tbl1_41'},
 {'ChartType': 'Bar',
  'NewsMedia': 'The Economist',
  'Y_AxisLabel': 'r',
  'X_AxisLabel': '',
  'Y_GridLines': 'r',
  'ChartTitle': 'r',
  'LegendImplicit': '',
  'X_TickMarks': '',
  'Y_AxisTitle': 'r',
  'X_Axis': '',
  'DataLabel': '',
  'X_GridLines': 'r',
  'X_AxisTitle': 'r',
  'Y_Axis': 'r',
  'LegendExplicit': '',
  'Y_TickMarks': '',
  'Highlight': 'r',
  'Exp.text': '',
  'GNRD': '',
  'HRO': '',
  'RowSum': 8,
  'Modified': '',
  'Cropped': 'TRUE',
  'Resized': '',
  'URL': '<a href=https://www.economist.com/graphic-detail/2018/12/11/america-is-friendlier-to-foreigners-than-headlines-suggest> Link </a>',
  'id': 'tbl1_42'},
 {'ChartType': 'Bar',
  'NewsMedia': 'The Economist',
  'Y_AxisLabel': 'r',
  'X_AxisLabel': '',
  'Y_GridLines': 'r',
  'ChartTitle': 'r',
  'LegendImplicit': '',
  'X_TickMarks': 'r',
  'Y_AxisTitle': 'r',
  'X_Axis': '',
  'DataLabel': '',
  'X_GridLines': '',
  'X_AxisTitle': 'r',
  'Y_Axis': '',
  'LegendExplicit': 'r',
  'Y_TickMarks': '',
  'Highlight': '',
  'Exp.text': 'r',
  'GNRD': '',
  'HRO': '',
  'RowSum': 8,
  'Modified': '',
  'Cropped': 'TRUE',
  'Resized': '',
  'URL': '<a href=https://www.economist.com/graphic-detail/2018/11/03/how-to-forecast-an-americans-vote> Link </a>',
  'id': 'tbl1_43'},
 {'ChartType': 'Bar',
  'NewsMedia': 'The Economist',
  'Y_AxisLabel': 'r',
  'X_AxisLabel': 'r',
  'Y_GridLines': 'r',
  'ChartTitle': 'r',
  'LegendImplicit': '',
  'X_TickMarks': '',
  'Y_AxisTitle': '',
  'X_Axis': '',
  'DataLabel': '',
  'X_GridLines': 'r',
  'X_AxisTitle': 'r',
  'Y_Axis': 'r',
  'LegendExplicit': '',
  'Y_TickMarks': '',
  'Highlight': '',
  'Exp.text': 'r',
  'GNRD': '',
  'HRO': '',
  'RowSum': 8,
  'Modified': '',
  'Cropped': '',
  'Resized': 'TRUE',
  'URL': '<a href=https://www.economist.com/graphic-detail/2018/11/09/pilots-are-not-high-flyers-when-it-comes-to-english-proficiency> Link </a>',
  'id': 'tbl1_44'},
 {'ChartType': 'Bar',
  'NewsMedia': 'The Economist',
  'Y_AxisLabel': 'r',
  'X_AxisLabel': '',
  'Y_GridLines': 'r',
  'ChartTitle': 'r',
  'LegendImplicit': '',
  'X_TickMarks': '',
  'Y_AxisTitle': '',
  'X_Axis': '',
  'DataLabel': '',
  'X_GridLines': 'r',
  'X_AxisTitle': 'r',
  'Y_Axis': 'r',
  'LegendExplicit': '',
  'Y_TickMarks': '',
  'Highlight': '',
  'Exp.text': '',
  'GNRD': '',
  'HRO': '',
  'RowSum': 6,
  'Modified': '',
  'Cropped': '',
  'Resized': 'TRUE',
  'URL': '<a href=https://www.economist.com/technology-quarterly/2018/12/01/how-to-get-the-carbon-out-of-industry> Link </a>',
  'id': 'tbl1_45'},
 {'ChartType': 'Bar',
  'NewsMedia': 'The Economist',
  'Y_AxisLabel': 'r',
  'X_AxisLabel': '',
  'Y_GridLines': 'e',
  'ChartTitle': 'r',
  'LegendImplicit': '',
  'X_TickMarks': 'e',
  'Y_AxisTitle': 'r',
  'X_Axis': 'e',
  'DataLabel': '',
  'X_GridLines': '',
  'X_AxisTitle': '',
  'Y_Axis': '',
  'LegendExplicit': 'r',
  'Y_TickMarks': 'e',
  'Highlight': 'e',
  'Exp.text': 'r',
  'GNRD': '',
  'HRO': '',
  'RowSum': 5,
  'Modified': 'TRUE',
  'Cropped': 'TRUE',
  'Resized': '',
  'URL': '<a href=https://www.economist.com/graphic-detail/2018/11/08/which-countries-are-most-likely-to-fight-wars> Link </a>',
  'id': 'tbl1_46'},
 {'ChartType': 'Bar',
  'NewsMedia': 'The New York Times',
  'Y_AxisLabel': 'r',
  'X_AxisLabel': 'r',
  'Y_GridLines': 'r',
  'ChartTitle': 'e',
  'LegendImplicit': '',
  'X_TickMarks': 'r',
  'Y_AxisTitle': 'e',
  'X_Axis': 'r',
  'DataLabel': '',
  'X_GridLines': '',
  'X_AxisTitle': '',
  'Y_Axis': '',
  'LegendExplicit': '',
  'Y_TickMarks': '',
  'Highlight': 'r',
  'Exp.text': 'r',
  'GNRD': '',
  'HRO': '',
  'RowSum': 7,
  'Modified': 'TRUE',
  'Cropped': '',
  'Resized': '',
  'URL': '<a href=https://www.nytimes.com/2018/12/07/business/economy/jobs-report.html> Link </a>',
  'id': 'tbl1_47'},
 {'ChartType': 'Bar',
  'NewsMedia': 'The New York Times',
  'Y_AxisLabel': 'r',
  'X_AxisLabel': '',
  'Y_GridLines': '',
  'ChartTitle': 'a',
  'LegendImplicit': 'r',
  'X_TickMarks': '',
  'Y_AxisTitle': '',
  'X_Axis': '',
  'DataLabel': 'r',
  'X_GridLines': '',
  'X_AxisTitle': '',
  'Y_Axis': '',
  'LegendExplicit': '',
  'Y_TickMarks': '',
  'Highlight': '',
  'Exp.text': 'r',
  'GNRD': '',
  'HRO': '',
  'RowSum': 5,
  'Modified': 'TRUE',
  'Cropped': '',
  'Resized': 'TRUE',
  'URL': '<a href=https://www.nytimes.com/2018/11/26/business/dealbook/stock-market-volatility.html> Link </a>',
  'id': 'tbl1_48'},
 {'ChartType': 'Bar',
  'NewsMedia': 'The New York Times',
  'Y_AxisLabel': '',
  'X_AxisLabel': '',
  'Y_GridLines': 'e',
  'ChartTitle': 'e',
  'LegendImplicit': '',
  'X_TickMarks': 'e',
  'Y_AxisTitle': '',
  'X_Axis': '',
  'DataLabel': '',
  'X_GridLines': '',
  'X_AxisTitle': '',
  'Y_Axis': '',
  'LegendExplicit': 'e',
  'Y_TickMarks': '',
  'Highlight': 'r',
  'Exp.text': 'r',
  'GNRD': '',
  'HRO': '',
  'RowSum': 2,
  'Modified': '',
  'Cropped': 'TRUE',
  'Resized': '',
  'URL': '<a href=https://www.nytimes.com/interactive/2018/11/10/upshot/republicans-dominate-state-politics-but-democrats-made-a-dent.html> Link </a>',
  'id': 'tbl1_49'},
 {'ChartType': 'Bar+Line',
  'NewsMedia': 'The Economist',
  'Y_AxisLabel': 'r',
  'X_AxisLabel': 'r',
  'Y_GridLines': 'r',
  'ChartTitle': 'r',
  'LegendImplicit': 'r',
  'X_TickMarks': 'r',
  'Y_AxisTitle': 'r',
  'X_Axis': 'r',
  'DataLabel': '',
  'X_GridLines': '',
  'X_AxisTitle': '',
  'Y_Axis': '',
  'LegendExplicit': 'r',
  'Y_TickMarks': '',
  'Highlight': '',
  'Exp.text': 'r',
  'GNRD': '',
  'HRO': '',
  'RowSum': 10,
  'Modified': '',
  'Cropped': '',
  'Resized': 'TRUE',
  'URL': '<a href=https://www.economist.com/graphic-detail/2018/11/28/the-three-countries-in-north-america-share-an-interconnected-economy> Link </a>',
  'id': 'tbl1_50'},
 {'ChartType': 'Bar+Line',
  'NewsMedia': 'The Economist',
  'Y_AxisLabel': 'r',
  'X_AxisLabel': 'r',
  'Y_GridLines': 'r',
  'ChartTitle': 'r',
  'LegendImplicit': '',
  'X_TickMarks': 'r',
  'Y_AxisTitle': 'r',
  'X_Axis': 'r',
  'DataLabel': '',
  'X_GridLines': '',
  'X_AxisTitle': '',
  'Y_Axis': '',
  'LegendExplicit': '',
  'Y_TickMarks': '',
  'Highlight': 'r',
  'Exp.text': 'r',
  'GNRD': '',
  'HRO': '',
  'RowSum': 9,
  'Modified': '',
  'Cropped': 'TRUE',
  'Resized': '',
  'URL': '<a href=https://www.economist.com/graphic-detail/2018/11/30/americas-treasury-is-earning-billions-from-donald-trumps-trade-war> Link </a>',
  'id': 'tbl1_51'},
 {'ChartType': 'Bar+Line',
  'NewsMedia': 'The Economist',
  'Y_AxisLabel': 'r',
  'X_AxisLabel': 'r',
  'Y_GridLines': 'r',
  'ChartTitle': 'r',
  'LegendImplicit': '',
  'X_TickMarks': 'r',
  'Y_AxisTitle': 'r',
  'X_Axis': 'r',
  'DataLabel': '',
  'X_GridLines': '',
  'X_AxisTitle': '',
  'Y_Axis': '',
  'LegendExplicit': '',
  'Y_TickMarks': '',
  'Highlight': '',
  'Exp.text': 'r',
  'GNRD': '',
  'HRO': '',
  'RowSum': 8,
  'Modified': '',
  'Cropped': '',
  'Resized': 'TRUE',
  'URL': '<a href=https://www.economist.com/graphic-detail/2018/11/19/why-men-who-make-less-than-their-wives-lie-about-their-earnings> Link </a>',
  'id': 'tbl1_52'},
 {'ChartType': 'Bar+Line',
  'NewsMedia': 'The Wall Street Journal',
  'Y_AxisLabel': '',
  'X_AxisLabel': 'r',
  'Y_GridLines': '',
  'ChartTitle': '',
  'LegendImplicit': '',
  'X_TickMarks': '',
  'Y_AxisTitle': '',
  'X_Axis': '',
  'DataLabel': '',
  'X_GridLines': '',
  'X_AxisTitle': '',
  'Y_Axis': '',
  'LegendExplicit': '',
  'Y_TickMarks': '',
  'Highlight': 'r',
  'Exp.text': 'r',
  'GNRD': 'r',
  'HRO': '',
  'RowSum': 4,
  'Modified': '',
  'Cropped': 'TRUE',
  'Resized': '',
  'URL': '<a href=https://www.wsj.com/graphics/bear-market-signs/> Link </a>',
  'id': 'tbl1_53'},
 {'ChartType': 'Bubble',
  'NewsMedia': 'Bloomberg',
  'Y_AxisLabel': 'r',
  'X_AxisLabel': 'r',
  'Y_GridLines': 'e',
  'ChartTitle': 'e',
  'LegendImplicit': 'r',
  'X_TickMarks': 'e',
  'Y_AxisTitle': 'e',
  'X_Axis': 'e',
  'DataLabel': 'r',
  'X_GridLines': '',
  'X_AxisTitle': 'e',
  'Y_Axis': '',
  'LegendExplicit': 'e',
  'Y_TickMarks': '',
  'Highlight': 'r',
  'Exp.text': 'e',
  'GNRD': '',
  'HRO': '',
  'RowSum': 5,
  'Modified': 'TRUE',
  'Cropped': 'TRUE',
  'Resized': '',
  'URL': '<a href=https://www.BBG.com/graphics/2018-carbon-pricing/> Link </a>',
  'id': 'tbl1_54'},
 {'ChartType': 'Bubble',
  'NewsMedia': 'The Economist',
  'Y_AxisLabel': '',
  'X_AxisLabel': '',
  'Y_GridLines': '',
  'ChartTitle': 'e',
  'LegendImplicit': '',
  'X_TickMarks': '',
  'Y_AxisTitle': '',
  'X_Axis': '',
  'DataLabel': '',
  'X_GridLines': '',
  'X_AxisTitle': '',
  'Y_Axis': '',
  'LegendExplicit': 'e',
  'Y_TickMarks': '',
  'Highlight': 'r',
  'Exp.text': 'r',
  'GNRD': '',
  'HRO': '',
  'RowSum': 2,
  'Modified': 'TRUE',
  'Cropped': '',
  'Resized': '',
  'URL': '<a href=https://www.economist.com/graphic-detail/2018/12/01/europeans-sour-on-elites-and-the-eu-but-agree-on-little-else> Link </a>',
  'id': 'tbl1_55'},
 {'ChartType': 'Scatterplot',
  'NewsMedia': 'Bloomberg',
  'Y_AxisLabel': 'r',
  'X_AxisLabel': 'r',
  'Y_GridLines': 'r',
  'ChartTitle': 'e',
  'LegendImplicit': 'r',
  'X_TickMarks': 'e',
  'Y_AxisTitle': 'e',
  'X_Axis': 'r',
  'DataLabel': '',
  'X_GridLines': '',
  'X_AxisTitle': 'e',
  'Y_Axis': 'r',
  'LegendExplicit': '',
  'Y_TickMarks': '',
  'Highlight': 'r',
  'Exp.text': 'e',
  'GNRD': '',
  'HRO': '',
  'RowSum': 7,
  'Modified': 'TRUE',
  'Cropped': 'TRUE',
  'Resized': '',
  'URL': '<a href=https://www.BBG.com/graphics/2018-midterm-election-turnout-shifts/> Link </a>',
  'id': 'tbl1_56'},
 {'ChartType': 'Scatterplot',
  'NewsMedia': 'FiveThirtyEight',
  'Y_AxisLabel': 'e',
  'X_AxisLabel': 'r',
  'Y_GridLines': 'e',
  'ChartTitle': '',
  'LegendImplicit': '',
  'X_TickMarks': '',
  'Y_AxisTitle': 'e',
  'X_Axis': 'e',
  'DataLabel': '',
  'X_GridLines': 'r',
  'X_AxisTitle': 'e',
  'Y_Axis': 'e',
  'LegendExplicit': 'e',
  'Y_TickMarks': '',
  'Highlight': 'e',
  'Exp.text': 'e',
  'GNRD': '',
  'HRO': '',
  'RowSum': 2,
  'Modified': 'TRUE',
  'Cropped': '',
  'Resized': '',
  'URL': '<a href=https://fivethirtyeight.com/features/no-democrats-didnt-win-the-senate-but-they-did-better-than-it-seems/> Link </a>',
  'id': 'tbl1_57'},
 {'ChartType': 'Scatterplot',
  'NewsMedia': 'FiveThirtyEight',
  'Y_AxisLabel': 'e',
  'X_AxisLabel': 'r',
  'Y_GridLines': 'e',
  'ChartTitle': 'e',
  'LegendImplicit': '',
  'X_TickMarks': '',
  'Y_AxisTitle': 'e',
  'X_Axis': 'e',
  'DataLabel': '',
  'X_GridLines': 'r',
  'X_AxisTitle': 'e',
  'Y_Axis': 'e',
  'LegendExplicit': '',
  'Y_TickMarks': '',
  'Highlight': '',
  'Exp.text': '',
  'GNRD': 'a',
  'HRO': '',
  'RowSum': 3,
  'Modified': 'TRUE',
  'Cropped': '',
  'Resized': '',
  'URL': '<a href=https://fivethirtyeight.com/features/everything-is-partisan-and-correlated-and-boring/> Link </a>',
  'id': 'tbl1_58'},
 {'ChartType': 'Scatterplot',
  'NewsMedia': 'The Economist',
  'Y_AxisLabel': 'r',
  'X_AxisLabel': 'r',
  'Y_GridLines': 'r',
  'ChartTitle': 'r',
  'LegendImplicit': '',
  'X_TickMarks': '',
  'Y_AxisTitle': 'r',
  'X_Axis': 'r',
  'DataLabel': '',
  'X_GridLines': 'r',
  'X_AxisTitle': 'r',
  'Y_Axis': '',
  'LegendExplicit': '',
  'Y_TickMarks': '',
  'Highlight': 'r',
  'Exp.text': 'r',
  'GNRD': 'a',
  'HRO': '',
  'RowSum': 11,
  'Modified': '',
  'Cropped': '',
  'Resized': 'TRUE',
  'URL': '<a href=https://www.economist.com/graphic-detail/2018/11/17/despite-californias-inferno-global-wildfires-are-fizzling-out> Link </a>',
  'id': 'tbl1_59'},
 {'ChartType': 'Scatterplot',
  'NewsMedia': 'The Economist',
  'Y_AxisLabel': 'r',
  'X_AxisLabel': 'r',
  'Y_GridLines': 'e',
  'ChartTitle': 'r',
  'LegendImplicit': '',
  'X_TickMarks': '',
  'Y_AxisTitle': 'r',
  'X_Axis': '',
  'DataLabel': '',
  'X_GridLines': 'r',
  'X_AxisTitle': 'r',
  'Y_Axis': '',
  'LegendExplicit': 'r',
  'Y_TickMarks': '',
  'Highlight': 'r',
  'Exp.text': 'r',
  'GNRD': '',
  'HRO': '',
  'RowSum': 9,
  'Modified': '',
  'Cropped': 'TRUE',
  'Resized': '',
  'URL': '<a href=https://www.economist.com/graphic-detail/2018/11/16/obama-trump-voters-turn-back-to-democrats> Link </a>',
  'id': 'tbl1_60'},
 {'ChartType': 'Scatterplot',
  'NewsMedia': 'The Economist',
  'Y_AxisLabel': 'r',
  'X_AxisLabel': 'r',
  'Y_GridLines': 'r',
  'ChartTitle': 'r',
  'LegendImplicit': '',
  'X_TickMarks': 'r',
  'Y_AxisTitle': '',
  'X_Axis': '',
  'DataLabel': 'r',
  'X_GridLines': '',
  'X_AxisTitle': 'r',
  'Y_Axis': '',
  'LegendExplicit': '',
  'Y_TickMarks': '',
  'Highlight': 'r',
  'Exp.text': 'r',
  'GNRD': '',
  'HRO': '',
  'RowSum': 9,
  'Modified': '',
  'Cropped': 'TRUE',
  'Resized': '',
  'URL': '<a href=https://www.economist.com/graphic-detail/2018/11/22/american-dietary-preferences-are-split-across-party-lines> Link </a>',
  'id': 'tbl1_61'},
 {'ChartType': 'Scatterplot',
  'NewsMedia': 'The Economist',
  'Y_AxisLabel': 'r',
  'X_AxisLabel': '',
  'Y_GridLines': 'r',
  'ChartTitle': 'r',
  'LegendImplicit': 'r',
  'X_TickMarks': '',
  'Y_AxisTitle': 'r',
  'X_Axis': '',
  'DataLabel': '',
  'X_GridLines': 'r',
  'X_AxisTitle': '',
  'Y_Axis': '',
  'LegendExplicit': '',
  'Y_TickMarks': 'r',
  'Highlight': 'r',
  'Exp.text': 'r',
  'GNRD': '',
  'HRO': '',
  'RowSum': 9,
  'Modified': 'TRUE',
  'Cropped': '',
  'Resized': '',
  'URL': '<a href=https://www.economist.com/graphic-detail/2018/11/24/tvs-golden-age-is-real> Link </a>',
  'id': 'tbl1_62'},
 {'ChartType': 'Scatterplot',
  'NewsMedia': 'The Economist',
  'Y_AxisLabel': 'e',
  'X_AxisLabel': 'e',
  'Y_GridLines': 'e',
  'ChartTitle': 'e',
  'LegendImplicit': 'r',
  'X_TickMarks': 'e',
  'Y_AxisTitle': '',
  'X_Axis': 'e',
  'DataLabel': '',
  'X_GridLines': 'e',
  'X_AxisTitle': '',
  'Y_Axis': '',
  'LegendExplicit': 'e',
  'Y_TickMarks': '',
  'Highlight': '',
  'Exp.text': 'e',
  'GNRD': '',
  'HRO': '',
  'RowSum': 1,
  'Modified': 'TRUE',
  'Cropped': '',
  'Resized': '',
  'URL': '<a href=https://www.economist.com/graphic-detail/2018/11/05/donald-trumps-presidential-approval-ratings> Link </a>',
  'id': 'tbl1_63'},
 {'ChartType': 'Scatterplot',
  'NewsMedia': 'The New York Times',
  'Y_AxisLabel': 'e',
  'X_AxisLabel': 'r',
  'Y_GridLines': 'e',
  'ChartTitle': 'e',
  'LegendImplicit': 'r',
  'X_TickMarks': '',
  'Y_AxisTitle': '',
  'X_Axis': 'r',
  'DataLabel': '',
  'X_GridLines': 'r',
  'X_AxisTitle': '',
  'Y_Axis': 'r',
  'LegendExplicit': '',
  'Y_TickMarks': '',
  'Highlight': 'r',
  'Exp.text': 'r',
  'GNRD': '',
  'HRO': '',
  'RowSum': 7,
  'Modified': '',
  'Cropped': 'TRUE',
  'Resized': '',
  'URL': '<a href=https://www.nytimes.com/2018/11/21/upshot/polls-2018-midterms-accuracy.html> Link </a>',
  'id': 'tbl1_64'},
 {'ChartType': 'Scatterplot',
  'NewsMedia': 'The New York Times',
  'Y_AxisLabel': 'r',
  'X_AxisLabel': 'r',
  'Y_GridLines': 'e',
  'ChartTitle': 'e',
  'LegendImplicit': '',
  'X_TickMarks': '',
  'Y_AxisTitle': '',
  'X_Axis': 'r',
  'DataLabel': '',
  'X_GridLines': '',
  'X_AxisTitle': '',
  'Y_Axis': '',
  'LegendExplicit': 'e',
  'Y_TickMarks': '',
  'Highlight': 'r',
  'Exp.text': 'r',
  'GNRD': '',
  'HRO': '',
  'RowSum': 5,
  'Modified': 'TRUE',
  'Cropped': '',
  'Resized': '',
  'URL': '<a href=https://www.nytimes.com/2018/11/26/upshot/suburbs-changing-midterms-democrats-hopes.html> Link </a>',
  'id': 'tbl1_65'},
 {'ChartType': 'Dot Plot',
  'NewsMedia': 'The Economist',
  'Y_AxisLabel': 'r',
  'X_AxisLabel': 'r',
  'Y_GridLines': 'r',
  'ChartTitle': 'r',
  'LegendImplicit': '',
  'X_TickMarks': '',
  'Y_AxisTitle': '',
  'X_Axis': '',
  'DataLabel': '',
  'X_GridLines': 'r',
  'X_AxisTitle': 'r',
  'Y_Axis': 'r',
  'LegendExplicit': 'r',
  'Y_TickMarks': '',
  'Highlight': '',
  'Exp.text': '',
  'GNRD': '',
  'HRO': '',
  'RowSum': 8,
  'Modified': '',
  'Cropped': 'TRUE',
  'Resized': '',
  'URL': '<a href=https://www.economist.com/graphic-detail/2018/11/27/people-underestimate-teachers-hours-and-say-they-should-be-paid-more> Link </a>',
  'id': 'tbl1_66'},
 {'ChartType': 'Pictogram chart',
  'NewsMedia': 'The New York Times',
  'Y_AxisLabel': 'r',
  'X_AxisLabel': 'r',
  'Y_GridLines': '',
  'ChartTitle': 'r',
  'LegendImplicit': '',
  'X_TickMarks': '',
  'Y_AxisTitle': '',
  'X_Axis': 'e',
  'DataLabel': 'r',
  'X_GridLines': '',
  'X_AxisTitle': '',
  'Y_Axis': '',
  'LegendExplicit': 'r',
  'Y_TickMarks': '',
  'Highlight': 'e',
  'Exp.text': 'r',
  'GNRD': 'r',
  'HRO': 'r',
  'RowSum': 8,
  'Modified': '',
  'Cropped': 'TRUE',
  'Resized': '',
  'URL': '<a href=https://www.nytimes.com/2018/11/07/upshot/2018-midterms-blue-wave-democrats.html> Link </a>',
  'id': 'tbl1_67'}];

var data2 = [{'Chart Type': 'Map',
 'News media': 'Bloomberg',
 'Edited': 'TRUE',
 'Cropped': 0,
 'Resized': 0,
 'URL': '<a href=https://www.bloomberg.com/graphics/2017-japan-inequality/> Link </a>',
 'id': 'tbl2_1'},
 {'Chart Type': 'Map',
  'News media': 'Bloomberg',
  'Edited': 0,
  'Cropped': 'TRUE',
  'Resized': 0,
  'URL': '<a href=https://www.bloomberg.com/graphics/pessimists-guide-to-2019/> Link </a>',
  'id': 'tbl2_2'},
 {'Chart Type': 'Map',
  'News media': 'Bloomberg',
  'Edited': 0,
  'Cropped': 0,
  'Resized': 'TRUE',
  'URL': '<a href=https://www.bloomberg.com/graphics/2018-amtrak-sea-level/> Link </a>',
  'id': 'tbl2_3'},
 {'Chart Type': 'Map',
  'News media': 'Bloomberg',
  'Edited': 0,
  'Cropped': 'TRUE',
  'Resized': 0,
  'URL': '<a href=https://www.bloomberg.com/graphics/2018-what-the-midterm-campaign-looks-like-in-your-hometown/> Link </a>',
  'id': 'tbl2_4'},
 {'Chart Type': 'Map',
  'News media': 'Bloomberg',
  'Edited': 'TRUE',
  'Cropped': 0,
  'Resized': 0,
  'URL': '<a href=https://www.bloomberg.com/graphics/2018-venezuela-oil/> Link </a>',
  'id': 'tbl2_5'},
 {'Chart Type': 'Map',
  'News media': 'Bloomberg',
  'Edited': 0,
  'Cropped': 'TRUE',
  'Resized': 0,
  'URL': '<a href=https://www.bloomberg.com/graphics/2018-us-gun-imports/> Link </a>',
  'id': 'tbl2_6'},
 {'Chart Type': 'Map',
  'News media': 'Pew Research Center',
  'Edited': 0,
  'Cropped': 'TRUE',
  'Resized': 0,
  'URL': '<a href=http://www.pewresearch.org/fact-tank/2018/12/05/how-do-european-countries-differ-in-religious-commitment/> Link </a>',
  'id': 'tbl2_7'},
 {'Chart Type': 'Map',
  'News media': 'The Economist',
  'Edited': 'TRUE',
  'Cropped': 0,
  'Resized': 0,
  'URL': '<a href=https://www.economist.com/graphic-detail/2018/12/01/europeans-sour-on-elites-and-the-eu-but-agree-on-little-else> Link </a>',
  'id': 'tbl2_8'},
 {'Chart Type': 'Map',
  'News media': 'The Economist',
  'Edited': 'TRUE',
  'Cropped': 0,
  'Resized': 0,
  'URL': '<a href=https://www.economist.com/graphic-detail/2018/12/18/what-does-the-irish-border-have-to-do-with-brexit> Link </a>',
  'id': 'tbl2_9'},
 {'Chart Type': 'Map',
  'News media': 'The Economist',
  'Edited': 0,
  'Cropped': 'TRUE',
  'Resized': 0,
  'URL': '<a href=https://www.economist.com/graphic-detail/2018/11/21/imperial-borders-still-shape-politics-in-poland-and-romania> Link </a>',
  'id': 'tbl2_10'},
 {'Chart Type': 'Map',
  'News media': 'The Economist',
  'Edited': 0,
  'Cropped': 'TRUE',
  'Resized': 0,
  'URL': '<a href=https://www.economist.com/graphic-detail/2018/12/27/is-there-any-truth-to-the-idea-of-midwestern-nice> Link </a>',
  'id': 'tbl2_11'},
 {'Chart Type': 'Map',
  'News media': 'The New York Times',
  'Edited': 0,
  'Cropped': 'TRUE',
  'Resized': 0,
  'URL': '<a href=https://www.nytimes.com/2018/11/09/upshot/florida-senate-race-broward-undercount.html> Link </a>',
  'id': 'tbl2_12'},
 {'Chart Type': 'Map',
  'News media': 'The New York Times',
  'Edited': 0,
  'Cropped': 'TRUE',
  'Resized': 0,
  'URL': '<a href=https://www.nytimes.com/interactive/2018/11/10/upshot/republicans-dominate-state-politics-but-democrats-made-a-dent.html> Link </a>',
  'id': 'tbl2_13'},
 {'Chart Type': 'Map',
  'News media': 'The New York Times',
  'Edited': 'TRUE',
  'Cropped': 0,
  'Resized': 0,
  'URL': '<a href=https://www.nytimes.com/2018/12/07/upshot/mapped-why-voting-anomalies-are-impossible-to-ignore-in-north-carolina.html> Link </a>',
  'id': 'tbl2_14'},
 {'Chart Type': 'Map',
  'News media': 'The New York Times',
  'Edited': 0,
  'Cropped': 0,
  'Resized': 'TRUE',
  'URL': '<a href=https://www.nytimes.com/2018/11/05/upshot/two-vastly-different-election-outcomes-that-hinge-on-a-few-dozen-close-contests.html> Link </a>',
  'id': 'tbl2_15'},
 {'Chart Type': 'Map',
  'News media': 'The New York Times',
  'Edited': 0,
  'Cropped': 'TRUE',
  'Resized': 0,
  'URL': '<a href=https://www.nytimes.com/interactive/2018/11/16/upshot/california-smoke-map.html> Link </a>',
  'id': 'tbl2_16'},
 {'Chart Type': 'Map',
  'News media': 'The Wall Street Journal',
  'Edited': 'TRUE',
  'Cropped': 0,
  'Resized': 0,
  'URL': '<a href=https://www.wsj.com/graphics/midterm-house-races-2018/> Link </a>',
  'id': 'tbl2_17'},
 {'Chart Type': 'Pie chart',
  'News media': 'First Tuesday Journal',
  'Edited': 0,
  'Cropped': 0,
  'Resized': 'TRUE',
  'URL': '<a href=http://journal.firsttuesday.us/the-votes-are-in-undisclosed-referral-fees-are-illegal-kickbacks/65875/> Link </a>',
  'id': 'tbl2_18'},
 {'Chart Type': 'Pie chart',
  'News media': 'The New York Times',
  'Edited': 0,
  'Cropped': 'TRUE',
  'Resized': 0,
  'URL': '<a href=https://www.nytimes.com/2018/11/05/upshot/needle-election-night-2018-midterms.html> Link </a>',
  'id': 'tbl2_19'},
 {'Chart Type': 'PCP',
  'News media': 'FiveThirtyEight',
  'Edited': 'TRUE',
  'Cropped': 0,
  'Resized': 0,
  'URL': '<a href=https://fivethirtyeight.com/features/americas-electoral-map-is-changing/> Link </a>',
  'id': 'tbl2_20'},
 {'Chart Type': 'Radical col.',
  'News media': 'The Economist',
  'Edited': 0,
  'Cropped': 'TRUE',
  'Resized': 0,
  'URL': '<a href=https://www.economist.com/graphic-detail/2018/12/08/why-ticket-prices-on-long-haul-flights-have-plummeted> Link </a>',
  'id': 'tbl2_21'},
 {'Chart Type': 'Sankey',
  'News media': 'Bloomberg',
  'Edited': 0,
  'Cropped': 'TRUE',
  'Resized': 0,
  'URL': '<a href=https://www.bloomberg.com/graphics/2018-recovering-madoff-money/> Link </a>',
  'id': 'tbl2_22'},
 {'Chart Type': 'Bar+Line+Map',
  'News media': 'Pew Research Center',
  'Edited': 'TRUE',
  'Cropped': 'TRUE',
  'Resized': 0,
  'URL': '<a href=http://www.pewresearch.org/fact-tank/2018/12/13/18-striking-findings-from-2018/> Link </a>',
  'id': 'tbl2_23'},
 {'Chart Type': 'Line+Map',
  'News media': 'The Economist',
  'Edited': 0,
  'Cropped': 'TRUE',
  'Resized': 0,
  'URL': '<a href=https://www.economist.com/graphic-detail/2018/11/13/knife-crime-in-britain-is-rising-almost-everywhere> Link </a>',
  'id': 'tbl2_24'}];

